# Generated by Django 5.1.5 on 2025-01-29 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_743fca_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created'], name='orders_orde_created_51311f_idx'),
        ),
    ]
